### ISSUE TITLE
Host.json error on new try function apps

### ISSUE THREAD

**Issue by fashaikh** [fashaikh/azure-functions-ux#1]
Environment URL: https://tryfunctions.com/try Browser: Chrome
Please refer to the snapshot: 
![image](https://user-images.githubusercontent.com/2650941/46818876-1d1aef80-cd37-11e8-87f0-f598f532d7e6.png)

Repro steps:
Open https://tryfunctions.com/try.
Select any Scenario and Language
Select any social auth provider and Enter social auth credentials;
Click "Create this function", verify the created function.

**Comment by brettsam** [comment]
@fashaikh -- do you know if anyone has looked at this issue yet?

**Comment by fashaikh** [comment]
Yes. Its fixed now.
had to pin functions extension version to 1.0 instead of latest to get over the breaking changes in 2.0
